# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190128_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
