# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190128_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='default value', max_length=30),
            preserve_default=False,
        ),
    ]
